name: tests
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19', '1.13']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Go Version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          go build ./...
      - name: Go Vet
        run: |
          go vet ./...
      - name: Go Fmt
        run: |
          test "0" = $(gofmt -d . | wc -l)
      - name: Go Test
        run: |
          go test ./...
  static-check:
    name: "static-check-linter-2022.1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
